clc;
clear all;
close all;
t1=-5:1:5;
y1=[zeros(1,5),ones(1,1),zeros(1,5)];
subplot(3,3,1);
stem(t1,y1);
xlabel('time index');
ylabel('amplitude');
title('unit impulse');
t2=0:0.1:1;
f2=5;
y2=square(2*pi*f2*t2);
subplot(3,3,2);
stem(t2,y2);
hold on;
plot(t2,y2);
xlabel('Time');
ylabel('Amplitude');
title('bipolar pulse');
axis([0 1 -2 2]);
legend('continuous','discrete','Location','best');
t3=0:0.1:1;
f3=5;
y3=sqrt(square(2*pi*f3*t3));
subplot(3,3,3);
stem(t3,y3);
hold on;
plot(t3,y3);
xlabel('Time');
ylabel('Amplitude');
title('unipolar pulse');
axis([0 1 -2 2]);
legend('continuous','discrete','Location','best');
t4=0:1:5;
y4=t4;
subplot(3,3,4);
stem(t4,y4);
hold on;
plot(t4,y4);
xlabel('Time');
ylabel('Amplitude');
legend('continuous','discrete');
title('Ramp signal');
f5=10;
t5=0:0.025:1;
y5=sin(2*pi*f5*t5);
subplot(3,3,5);
stem(t5,y5);
hold on;
plot(t5,y5);
xlabel('time');
ylabel('amplitude');
title('triangular signal');
legend('continuous','discrete','best');
t6=0:0.01:1;
f6=5;
y6=sin(2*pi*f6*t6);
subplot(3,3,6);
stem(t6,y6);
hold on;
plot(t6,y6);
xlabel('time');
ylabel('amplitude');
title('sine wave');
legend('continuous','discrete');
t7=0:0.01:1;
f7=5;
y7=cos(2*pi*f7*t7);
subplot(3,3,7);
stem(t7,y7);
hold on;
plot(t7,y7);
xlabel('time');
ylabel('amplitude');
title('cosine wave');
legend('continuous','discrete');
t8=-5:1:5;
y8=exp(t8);
subplot(3,3,8);
stem(t8,y8);
hold on;
plot(t8,y8);
xlabel('time');
ylabel('amplitude');
legend('continuous','discrete')
title('exponential signal');
t9=-5:1:5;
y9=[zeros(1,5),ones(1,6)];
subplot(3,3,9);
hold on;
stem(t9,y9);
xlabel('time');
ylabel('amplitude');
axis([-5 5 0 2]);
title('unit step signal');



