clc;
clear all;
close all;
x = input('Enter input x(n): ');
x_ind = input('Enter index of x(n): ');
h = input('Enter input h(n):');
h_ind = input('Enter index of h(n):');
x_len = length(x);
h_len = length(h);
y_len = max(x_len,h_len);
newx = [x zeros(1,y_len-x_len)];
newh = [h zeros(1,y_len-h_len)];
x1 = fft(newx);
h1 = fft(newh);
hx = x1.*h1;
c = ifft(hx);
disp(c);
subplot(1,3,1);
stem(x_ind,x);
xlabel('time index');
ylabel('amplitude');
title('x(n)');
subplot(1,3,2);
stem(h_ind,h);
xlabel('time index');
ylabel('amplitude');
title('h(n)');
subplot(1,3,3);
stem([0:y_len-1],c);
xlabel('time index');
ylabel('amplitude');
title('Circular convoluted signal');
